language: php

php:
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest
    - WP_VERSION=3.8.1
    - WP_VERSION=3.7.1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
