language: php

php:
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest
    - WP_VERSION=4.0.1
    - WP_VERSION=3.9.3

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
