<?php

die(); //Don't actually run the following code.

echo __( 'Message #1' );
echo _x( 'Message #1' );
echo _n( 'Message #1' );
echo _nx( 'Message #1' );
echo( __( 'Message #1' ) );
echo( _x( 'Message #1' ) );
echo( _n( 'Message #1' ) );
echo( _nx( 'Message #1' ) );
print __( 'Message #1' );
print _x( 'Message #1' );
print _n( 'Message #1' );
print _nx( 'Message #1' );
print( __( 'Message #1' ) );
print( _x( 'Message #1' ) );
print( _n( 'Message #1' ) );
print( _nx( 'Message #1' ) );
vprintf ( __( 'Message #%d' ), 1 );
vprintf ( _x( 'Message #%d' ), 1 );
vprintf ( _n( 'Message #%d' ), 1 );
vprintf ( _nx( 'Message #%d' ), 1 );
__( 'Message #1' );
_x( 'Message #1' );
_n( 'Message #1' );
_nx( 'Message #1' );
_e( 'Message #1' );
_ex( 'Message #1' );
