<?php

// Uncached functions
count_user_posts();
get_category_by_slug();
wp_get_post_categories();
wp_get_post_tags();
get_cat_ID();
get_term_by();
get_page_by_title();
get_page_by_path();
wp_get_object_terms();
wp_get_post_terms();
get_posts();
wp_get_recent_posts();
get_children();
term_exists();
get_term_link();
get_tag_link();
get_category_link();
url_to_post_id();
url_to_postid();
wp_old_slug_redirect();
get_adjacent_post();
get_previous_post();
get_next_post();
previous_post_link();
next_post_link();
attachment_url_to_postid();

// Object cache bypass
wpcom_uncached_get_post_meta();
wpcom_uncached_get_post_by_meta();