<?php

abstract class BaseAnalyzer {
	/**
	 * @var array<AnalyzerMeta>
	 */
	protected $metas = array();

	/**
	 * @var array
	 */
	protected $stats = array();
	
	/**
	 * Runs the analyzer on the given $files.
	 * 
	 * @param array<AnalyzedFile> $files The files to process
	 */
	abstract function analyze( $files );
	
	/**
	 * Gets the metas generated by this analyzer.
	 * @return array<AnalyzerMeta>
	 */
	function get_metas() {
		return $this->metas;
	}

	/**
	 * Gets the stats generated by this analyzer.
	 * @return array
	 */
	function get_stats() {
		return $this->stats;
	}
}